// SUCCESSFUL RESPONSES
export const OK_STATUS = 200;
export const CREATED_STATUS = 201;

// CLIENT ERROR RESPONSES
export const BAD_REQUEST_STATUS = 400;
export const UNAUTHORIZED_STATUS = 401;
export const FORBIDDEN_STATUS = 403;
export const NOT_FOUND_STATUS = 404;
export const METHOD_NOT_ALLOWED = 405;

// SERVER ERROR RESPONSES
export const INTERNAL_SERVER_ERROR_STATUS = 500;
